<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Version>13.1.0</Version>
    <AssemblyVersion>13.1.0.0</AssemblyVersion>
    <FileVersion>13.1.0.0</FileVersion>
    <InformationalVersion>13.1.0+jellyfin.10.11</InformationalVersion>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Web\autoorganizelog.html" />
    <None Remove="Web\autoorganizelog.js" />
    <None Remove="Web\autoorganizemovie.html" />
    <None Remove="Web\autoorganizemovie.js" />
    <None Remove="Web\autoorganizesmart.html" />
    <None Remove="Web\autoorganizesmart.js" />
    <None Remove="Web\autoorganizetv.html" />
    <None Remove="Web\autoorganizetv.js" />
    <None Remove="Web\fileorganizer.js" />
    <None Remove="Web\fileorganizer.template.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\autoorganizelog.html" />
    <EmbeddedResource Include="Web\autoorganizelog.js" />
    <EmbeddedResource Include="Web\autoorganizesmart.html" />
    <EmbeddedResource Include="Web\autoorganizesmart.js" />
    <EmbeddedResource Include="Web\autoorganizemovie.html" />
    <EmbeddedResource Include="Web\autoorganizemovie.js" />
    <EmbeddedResource Include="Web\autoorganizetv.html" />
    <EmbeddedResource Include="Web\autoorganizetv.js" />
    <EmbeddedResource Include="Web\fileorganizer.js" />
    <EmbeddedResource Include="Web\fileorganizer.template.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Database.Implementations" Version="10.11.11" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.11" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Naming" Version="10.11.11" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.11" ExcludeAssets="runtime" />
    <PackageReference Include="SearchPioneer.Lingua" Version="1.0.5" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
